# Generated by Django 4.2 on 2023-07-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betcodes', '0004_rename_ticket_time_bookcodeinfo_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
